### PR TITLE
Remove SetFilterFilterCoefficientSet when adding SetTxFilterCoefficientSet

### PR DESCRIPTION
**Pull request by jamesobutler**
This is based on https://github.com/jrojasUNC/PlusLib/tree/juanrojas-add-new-winprobe-commands but is a force-pushed variant which removes `SetFilterFilterCoefficientSet` to be replaced by `SetTxFilterCoefficientSet`. I did not have rights to update this branch directly which is why I have posted this PR. cc: @jrojasUNC

### CODE REVIEW

**Comment by jamesobutler** [comment]
Feel free to reset https://github.com/jrojasUNC/PlusLib/tree/juanrojas-add-new-winprobe-commands and cherry-pick these commits into it. This PR could then be closed instead of technically integrated.

**Comment by jrojasUNC** [comment]
done

**Comment by jamesobutler** [comment]
@jrojasUNC There is another place to update where the following should be removed https://github.com/jrojasUNC/PlusLib/blob/ee2230a533d0b1ed3870fe13468568a3d96f8c0a/src/PlusServer/Commands/vtkPlusWinProbeCommand.cxx#L448

**Comment by jrojasUNC** [comment]
removed

**Pull request closed without merging**
